"""Match-identity and team-level metric families.

Covers `match_context`, `team_misc`, team-scoped `discipline`, and every
`team_performance` / `team_possession` / `team_set_pieces` / `team_pressing`
/ `team_transition` metric. The first block of entries in each family below
reproduces the exact `(key, granularity)` identity `coverage_lab` already
derives from `normalization.models.MatchRecord` / `TeamMatchStatsRecord` /
`TeamLineupRecord` (collapsed from `team_match` to `team` -- see
`metric_catalog.catalog._GRANULARITY_COLLAPSE`) -- never renamed, since
existing coverage rows and tests key on those exact strings.
"""

from __future__ import annotations

from football_intelligence.metric_catalog.types import CATALOG_V2_VERSION, MetricDefinition

_TEAM_MATCH_SAMPLE = "min 5 matches in window for percentile eligibility (team-v1.0 confidence)"
_TEAM_SEASON_SAMPLE = "season-level aggregate across the team's matches; no per-match denominator"
_IDENTITY_SAMPLE = "identity/context field; never compared across a population"

MATCH_AND_TEAM_METRICS: tuple[MetricDefinition, ...] = (
    # -- match_context (baseline: MatchRecord) -------------------------------
    MetricDefinition(
        key="kickoff_at",
        display_name="Kickoff Time",
        granularity="match",
        category="match_context",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="status",
        display_name="Match Status",
        granularity="match",
        category="match_context",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="round_name",
        display_name="Round / Matchday",
        granularity="match",
        category="match_context",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="venue_name",
        display_name="Venue",
        granularity="match",
        category="match_context",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="home_score",
        display_name="Home Goals",
        granularity="match",
        category="match_context",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="away_score",
        display_name="Away Goals",
        granularity="match",
        category="match_context",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- team_misc (baseline: TeamLineupRecord + 2 TeamMatchStatsRecord fields,
    #    plus 2 new season-level stability metrics) ---------------------------
    MetricDefinition(
        key="formation",
        display_name="Formation",
        granularity="team_match",
        category="team_misc",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="coach_name",
        display_name="Coach",
        granularity="team_match",
        category="team_misc",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_IDENTITY_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="offsides",
        display_name="Offsides (Team)",
        granularity="team_match",
        category="team_misc",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="fouls",
        display_name="Fouls Committed (Team)",
        granularity="team_match",
        category="team_misc",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="lineup_stability",
        display_name="Lineup Stability",
        granularity="team",
        category="team_misc",
        unit="rating",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_SEASON_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="Not wired into scoring yet; declared for future starting-XI turnover analysis.",
    ),
    MetricDefinition(
        key="formation_stability",
        display_name="Formation Stability",
        granularity="team",
        category="team_misc",
        unit="rating",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_SEASON_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="Not wired into scoring yet; declared for future tactical-identity analysis.",
    ),
    # -- discipline (team) ----------------------------------------------------
    MetricDefinition(
        key="yellow_cards",
        display_name="Yellow Cards (Team)",
        granularity="team_match",
        category="discipline",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="red_cards",
        display_name="Red Cards (Team)",
        granularity="team_match",
        category="discipline",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="V1 excludes red cards from team scoring due to unreliable coverage; catalog only.",
    ),
    # -- team_performance (baseline: 5 TeamMatchStatsRecord shot fields,
    #    plus 6 new goals/xG/shots-against metrics) ---------------------------
    MetricDefinition(
        key="shots_total",
        display_name="Shots (Team)",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shots_on_target",
        display_name="Shots on Target (Team)",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shots_inside_box",
        display_name="Shots Inside Box (Team)",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shots_outside_box",
        display_name="Shots Outside Box (Team)",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="blocked_shots",
        display_name="Blocked Shots (Team)",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="goals_for",
        display_name="Goals For",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="goals_against",
        display_name="Goals Against",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="xg",
        display_name="Expected Goals (Team)",
        granularity="team_match",
        category="team_performance",
        unit="rating",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="No zero-cost current-season provider reports team-level xG yet; catalog only.",
    ),
    MetricDefinition(
        key="xga",
        display_name="Expected Goals Against (Team)",
        granularity="team_match",
        category="team_performance",
        unit="rating",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="No zero-cost current-season provider reports team-level xGA yet; catalog only.",
    ),
    MetricDefinition(
        key="shots_allowed",
        display_name="Shots Conceded (Team)",
        granularity="team_match",
        category="team_performance",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="xg_per_shot",
        display_name="xG per Shot (Team)",
        granularity="team_match",
        category="team_performance",
        unit="rating",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- team_possession (baseline: possession_pct/passes_total/passes_accurate,
    #    plus 4 new possession/control metrics) -------------------------------
    MetricDefinition(
        key="possession_pct",
        display_name="Possession %",
        granularity="team_match",
        category="team_possession",
        unit="percentage",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="passes_total",
        display_name="Passes (Team)",
        granularity="team_match",
        category="team_possession",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="passes_accurate",
        display_name="Accurate Passes (Team)",
        granularity="team_match",
        category="team_possession",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="field_tilt",
        display_name="Field Tilt %",
        granularity="team_match",
        category="team_possession",
        unit="percentage",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="pass_accuracy_pct",
        display_name="Pass Accuracy % (Team)",
        granularity="team_match",
        category="team_possession",
        unit="percentage",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="progressive_passes",
        display_name="Progressive Passes (Team)",
        granularity="team_match",
        category="team_possession",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="final_third_entries",
        display_name="Final Third Entries (Team)",
        granularity="team_match",
        category="team_possession",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- team_set_pieces (baseline: corners, plus 2 new) ----------------------
    MetricDefinition(
        key="corners",
        display_name="Corners (Team)",
        granularity="team_match",
        category="team_set_pieces",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="set_piece_shots",
        display_name="Set-Piece Shots (Team)",
        granularity="team_match",
        category="team_set_pieces",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="set_piece_xg",
        display_name="Set-Piece xG (Team)",
        granularity="team_match",
        category="team_set_pieces",
        unit="rating",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- team_pressing (3 new) -------------------------------------------------
    MetricDefinition(
        key="recoveries",
        display_name="Ball Recoveries (Team)",
        granularity="team_match",
        category="team_pressing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="pressures",
        display_name="Pressures (Team)",
        granularity="team_match",
        category="team_pressing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="ppda",
        display_name="PPDA (Team)",
        granularity="team_match",
        category="team_pressing",
        unit="rating",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="Passes allowed per defensive action; lower means more intense pressing.",
    ),
    # -- team_transition (2 new) ----------------------------------------------
    MetricDefinition(
        key="counter_attacks",
        display_name="Counter-Attacks (Team)",
        granularity="team_match",
        category="team_transition",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="counter_attack_shots",
        display_name="Counter-Attack Shots (Team)",
        granularity="team_match",
        category="team_transition",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_TEAM_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
)
