"""Player participation, output, expected-output, and discipline metrics.

The `player_appearance` and first two `output`/`expected_output`/discipline
entries reproduce the exact `(key, granularity)` identity `coverage_lab`
already derives from `normalization.models.PlayerAppearanceRecord` /
`PlayerMatchStatsRecord` / the existing `advanced.xg` namespace entry --
never renamed. `advanced.xg` in particular keeps its historical dotted key
rather than being renamed to a bare `xg`, exactly as it already exists in
`coverage_lab.target_metrics.ADVANCED_METRICS`.
"""

from __future__ import annotations

from football_intelligence.metric_catalog.types import CATALOG_V2_VERSION, MetricDefinition

_APPEARANCE_SAMPLE = "identity/context field observed once per appearance; never compared as a rate"
_PLAYER_MATCH_SAMPLE = "min 450 minutes for percentile eligibility (player-v1.0 shrinkage prior)"
_PLAYER_SEASON_SAMPLE = "season-aggregate only; no per-match denominator"

PLAYER_CORE_METRICS: tuple[MetricDefinition, ...] = (
    # -- participation (baseline: PlayerAppearanceRecord) ---------------------
    MetricDefinition(
        key="minutes",
        display_name="Minutes Played",
        granularity="player_appearance",
        category="participation",
        unit="minutes",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_APPEARANCE_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="started",
        display_name="Started",
        granularity="player_appearance",
        category="participation",
        unit="boolean",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_APPEARANCE_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="captain",
        display_name="Captain",
        granularity="player_appearance",
        category="participation",
        unit="boolean",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_APPEARANCE_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shirt_number",
        display_name="Shirt Number",
        granularity="player_appearance",
        category="participation",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_APPEARANCE_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="listed_position",
        display_name="Listed Position",
        granularity="player_appearance",
        category="participation",
        unit="label",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_APPEARANCE_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="matches",
        display_name="Matches in Squad",
        granularity="player_season",
        category="participation",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_PLAYER_SEASON_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="appearances",
        display_name="Appearances",
        granularity="player_season",
        category="participation",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_PLAYER_SEASON_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="starts",
        display_name="Starts",
        granularity="player_season",
        category="participation",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_PLAYER_SEASON_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="sub_appearances",
        display_name="Substitute Appearances",
        granularity="player_season",
        category="participation",
        unit="count",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_PLAYER_SEASON_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="appearances - starts.",
    ),
    MetricDefinition(
        key="minutes_per_appearance",
        display_name="Minutes per Appearance",
        granularity="player_season",
        category="participation",
        unit="minutes",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_SEASON_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- output (baseline: goals, assists) -------------------------------------
    MetricDefinition(
        key="goals",
        display_name="Goals",
        granularity="player_match",
        category="output",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="assists",
        display_name="Assists",
        granularity="player_match",
        category="output",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="non_penalty_goals",
        display_name="Non-Penalty Goals",
        granularity="player_match",
        category="output",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="goal_contributions",
        display_name="Goal Contributions",
        granularity="player_match",
        category="output",
        unit="count",
        kind="derived",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="goals + assists.",
    ),
    MetricDefinition(
        key="penalty_goals",
        display_name="Penalty Goals",
        granularity="player_match",
        category="output",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="penalties_attempted",
        display_name="Penalties Attempted",
        granularity="player_match",
        category="output",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="penalties_missed",
        display_name="Penalties Missed",
        granularity="player_match",
        category="output",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- expected_output (baseline: advanced.xg) -------------------------------
    MetricDefinition(
        key="advanced.xg",
        display_name="Expected Goals (xG)",
        granularity="player_match",
        category="expected_output",
        unit="rating",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="Historical coverage_lab key preserved verbatim (never renamed to bare 'xg').",
    ),
    MetricDefinition(
        key="npxg",
        display_name="Non-Penalty Expected Goals",
        granularity="player_match",
        category="expected_output",
        unit="rating",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="xa",
        display_name="Expected Assists (xA)",
        granularity="player_match",
        category="expected_output",
        unit="rating",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="xg_plus_xa",
        display_name="xG + xA",
        granularity="player_match",
        category="expected_output",
        unit="rating",
        kind="derived",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="goals_minus_xg",
        display_name="Goals Minus xG",
        granularity="player_match",
        category="expected_output",
        unit="rating",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="Finishing-vs-process signal; not a skill claim (see diagnostics.finishing_*).",
    ),
    MetricDefinition(
        key="assists_minus_xa",
        display_name="Assists Minus xA",
        granularity="player_match",
        category="expected_output",
        unit="rating",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- discipline (player) ----------------------------------------------------
    MetricDefinition(
        key="yellow_cards",
        display_name="Yellow Cards",
        granularity="player_match",
        category="discipline",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="red_cards",
        display_name="Red Cards",
        granularity="player_match",
        category="discipline",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="second_yellow_cards",
        display_name="Second Yellow Cards",
        granularity="player_match",
        category="discipline",
        unit="count",
        kind="raw",
        per90_eligible=False,
        percentile_eligible=False,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
)
