"""Player technical-play metric families: shooting through duels.

The `shots_total`/`shots_on_target`/`key_passes`/`passes_total`/
`passes_accurate`/`dribbles_attempted`/`dribbles_successful`/`tackles`/
`blocks`/`interceptions`/`clearances`/`duels_total`/`duels_won`/
`fouls_drawn`/`fouls_committed` entries below reproduce the exact
`(key, granularity)` identity `coverage_lab` already derives from
`normalization.models.PlayerMatchStatsRecord` -- never renamed.

Only `FEATURE_METRICS` from `player_analytics.config` (goals, assists,
shots_total, shots_on_target, passes_total, key_passes, tackles, blocks,
interceptions, dribbles_successful, duels_won, fouls_drawn, fouls_committed,
saves) are wired into scoring today; every other metric declared here is
catalog-only until a real per-match data source exists for it (Block 16
scope -- see `docs/PLAYER_ANALYTICS.md`).
"""

from __future__ import annotations

from football_intelligence.metric_catalog.types import CATALOG_V2_VERSION, MetricDefinition

_PLAYER_MATCH_SAMPLE = "min 450 minutes for percentile eligibility (player-v1.0 shrinkage prior)"

PLAYER_TECHNICAL_METRICS: tuple[MetricDefinition, ...] = (
    # -- shooting (baseline: shots_total, shots_on_target) ---------------------
    MetricDefinition(
        key="shots_total",
        display_name="Shots",
        granularity="player_match",
        category="shooting",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shots_on_target",
        display_name="Shots on Target",
        granularity="player_match",
        category="shooting",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shots_off_target",
        display_name="Shots Off Target",
        granularity="player_match",
        category="shooting",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="blocked_shots",
        display_name="Shots Blocked",
        granularity="player_match",
        category="shooting",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shots_inside_box",
        display_name="Shots Inside Box",
        granularity="player_match",
        category="shooting",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="shots_on_target_pct",
        display_name="Shot Accuracy %",
        granularity="player_match",
        category="shooting",
        unit="percentage",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="xg_per_shot",
        display_name="xG per Shot",
        granularity="player_match",
        category="shooting",
        unit="rating",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="big_chances",
        display_name="Big Chances",
        granularity="player_match",
        category="shooting",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- creation (baseline: key_passes) ---------------------------------------
    MetricDefinition(
        key="key_passes",
        display_name="Key Passes",
        granularity="player_match",
        category="creation",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="chances_created",
        display_name="Chances Created",
        granularity="player_match",
        category="creation",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="big_chances_created",
        display_name="Big Chances Created",
        granularity="player_match",
        category="creation",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="passes_into_box",
        display_name="Passes Into Box",
        granularity="player_match",
        category="creation",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="through_balls",
        display_name="Through Balls",
        granularity="player_match",
        category="creation",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="crosses",
        display_name="Crosses",
        granularity="player_match",
        category="creation",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- passing (baseline: passes_total, passes_accurate) ---------------------
    MetricDefinition(
        key="passes_total",
        display_name="Passes",
        granularity="player_match",
        category="passing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="passes_accurate",
        display_name="Accurate Passes",
        granularity="player_match",
        category="passing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="pass_completion_pct",
        display_name="Pass Completion %",
        granularity="player_match",
        category="passing",
        unit="percentage",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="passes_short",
        display_name="Short Passes",
        granularity="player_match",
        category="passing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="passes_medium",
        display_name="Medium Passes",
        granularity="player_match",
        category="passing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="passes_long",
        display_name="Long Passes",
        granularity="player_match",
        category="passing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="progressive_passes",
        display_name="Progressive Passes",
        granularity="player_match",
        category="passing",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- progression / carrying (all new) --------------------------------------
    MetricDefinition(
        key="progressive_carries",
        display_name="Progressive Carries",
        granularity="player_match",
        category="progression",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="carries",
        display_name="Carries",
        granularity="player_match",
        category="progression",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="carries_into_final_third",
        display_name="Carries Into Final Third",
        granularity="player_match",
        category="progression",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- dribbling (baseline: dribbles_attempted, dribbles_successful) ---------
    MetricDefinition(
        key="dribbles_attempted",
        display_name="Dribbles Attempted",
        granularity="player_match",
        category="dribbling",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="dribbles_successful",
        display_name="Successful Dribbles",
        granularity="player_match",
        category="dribbling",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="dribble_success_pct",
        display_name="Dribble Success %",
        granularity="player_match",
        category="dribbling",
        unit="percentage",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="take_ons_attempted",
        display_name="Take-Ons Attempted",
        granularity="player_match",
        category="dribbling",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="take_ons_successful",
        display_name="Successful Take-Ons",
        granularity="player_match",
        category="dribbling",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- possession_security (all new) -----------------------------------------
    MetricDefinition(
        key="dispossessed",
        display_name="Dispossessed",
        granularity="player_match",
        category="possession_security",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="miscontrols",
        display_name="Miscontrols",
        granularity="player_match",
        category="possession_security",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="possession_losses",
        display_name="Possession Losses",
        granularity="player_match",
        category="possession_security",
        unit="count",
        kind="derived",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
        notes="dispossessed + miscontrols.",
    ),
    # -- defending (baseline: tackles, blocks, interceptions, clearances) -----
    MetricDefinition(
        key="tackles",
        display_name="Tackles",
        granularity="player_match",
        category="defending",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="blocks",
        display_name="Blocks",
        granularity="player_match",
        category="defending",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="interceptions",
        display_name="Interceptions",
        granularity="player_match",
        category="defending",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="clearances",
        display_name="Clearances",
        granularity="player_match",
        category="defending",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="tackles_won",
        display_name="Tackles Won",
        granularity="player_match",
        category="defending",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="tackle_success_pct",
        display_name="Tackle Success %",
        granularity="player_match",
        category="defending",
        unit="percentage",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="recoveries",
        display_name="Ball Recoveries",
        granularity="player_match",
        category="defending",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="pressures",
        display_name="Pressures",
        granularity="player_match",
        category="defending",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    # -- duels (baseline: duels_total, duels_won, fouls_drawn, fouls_committed)
    MetricDefinition(
        key="duels_total",
        display_name="Duels",
        granularity="player_match",
        category="duels",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="duels_won",
        display_name="Duels Won",
        granularity="player_match",
        category="duels",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="fouls_drawn",
        display_name="Fouls Drawn",
        granularity="player_match",
        category="duels",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="fouls_committed",
        display_name="Fouls Committed",
        granularity="player_match",
        category="duels",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="lower_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="duel_win_pct",
        display_name="Duel Win %",
        granularity="player_match",
        category="duels",
        unit="percentage",
        kind="derived",
        per90_eligible=False,
        percentile_eligible=True,
        direction="higher_better",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
    MetricDefinition(
        key="aerial_duels",
        display_name="Aerial Duels",
        granularity="player_match",
        category="duels",
        unit="count",
        kind="raw",
        per90_eligible=True,
        percentile_eligible=True,
        direction="contextual",
        min_sample_policy=_PLAYER_MATCH_SAMPLE,
        semantic_version=CATALOG_V2_VERSION,
    ),
)
